site_name: 与谁同坐
theme:
    name: mkdocs
    custom_dir: custom_theme/
nav:
    - '首页': 'index.md'
    - '旅行':
        - '古建筑': 'travel/gujianzhu.md'
        - '文物': 'travel/wenwu.md'
        - '地质': 'travel/dizhi.md'
    - '人与社会':
        - '发展': 'people/development.md'
        - '心理': 'people/psychology.md'
        - '生理': 'people/health.md'
        - '社会': 'people/society.md'
        - '政经': 'people/econ.md'
